# Winterfell for Alacritty
# ~/.config/alacritty/theme.yml
colors:
  primary:
    background: '#192329'
    foreground: '#9ab3c1'
    dim_foreground: '#6d91a5'
    bright_foreground: '#b0c4ce'
  cursor:
    text: '#192329'
    cursor: '#8ed084'
  vi_mode_cursor:
    text: '#192329'
    cursor: '#8ed084'
  search:
    matches:
      foreground: '#2d3f4a'
      background: '#a47efd'
    focused_match:
      foreground: '#a47efd'
      background: '#2d3f4a'
  hints:
    start:
      foreground: '#2d3f4a'
      background: '#d9c57a'
    end:
      foreground: '#d9c57a'
      background: '#2d3f4a'
  line_indicator:
    foreground: None
    background: None
  footer_bar:
    foreground: '#2d3f4a'
    background: '#a47efd'
  selection:
    text: '#9ab3c1'
    background: '#334855'
  normal:
    black: '#3f5867'
    red: '#df6265'
    green: '#8ed084'
    yellow: '#d9c57a'
    blue: '#62a5fd'
    magenta: '#f474bc'
    cyan: '#60b8d8'
    white: '#b0c4ce'
  bright:
    black: '#3f5867'
    red: '#df6265'
    green: '#8ed084'
    yellow: '#d9c57a'
    blue: '#62a5fd'
    magenta: '#f474bc'
    cyan: '#60b8d8'
    white: '#b0c4ce'
    