#!/bin/fish

sudo pacman -S --noconfirm --needed base-devel git fish rustup

# Install rustup toolchain
echo "Installing rustup with its stable toolchain ..."
rustup install stable
rustup default stable
echo "[DONE] Rustup installed."

sleep 1

# Install Paru
if which paru
  echo "[DONE] Paru detected."
else
  echo "Installing paru ..."
  git clone https://aur.archlinux.org/paru.git
  pushd paru
  makepkg -si --noconfirm
  popd
  rm -rf paru
  echo "[DONE] Paru installed."
end

sleep 1

echo "Refreshing repositories ..."
paru -Syy --noconfirm
paru -Sy --noconfirm archlinux-keyring

sleep 1

echo "Installing base packages ..."
paru -S --noconfirm --needed \
  base-devel \
  clang \
  curl \
  chromium \
  docker \
  docker-compose \
  docker-machine \
  fd \
  fish \
  fnm-bin \
  git \
  go \
  golangci-lint \
  gtk3 \
  gtk4 \
  jq \
  lf \
  luacheck \
  man \
  neovim \
  pdfjs \
  python-adblock \
  python-pip \
  qutebrowser \
  ripgrep \
  rsync \
  rustup \
  stylua \
  tree \
  unzip \
  xdg-utils \
  xdg-user-dirs \
  vscode

sleep 1

echo "Installing necessary packages ..."
paru -S --noconfirm --needed \
  alacritty \
  btop \
  breeze-snow-cursor-theme \
  glfw-wayland \
  grim \
  imagemagick \
  imv \
  papirus-icon-theme \
  qt5-wayland \
  qt6-wayland \
  rofi-lbonn-wayland-git \
  sddm \
  sddm-sugar-candy-git \
  slurp \
  starship \
  sway \
  swaybg \
  swaylock-effects-git \
  ttf-roboto \
  waybar \
  wf-recorder \
  wlr-randr \
  wlsunset \
  wl-clipboard \
  xorg-xwayland \
  xorg-xlsclients \
  zathura \
  zathura-pdf-poppler

echo "[DONE] Package installation completed."

sleep 1

# Enable systemd services
echo "Enabling services ..."
sudo systemctl enable sddm.service
echo "[DONE] System services enabled."

# SDDM
echo "Configuring SDDM.."
sudo rsync --recursive ./extras/sddm.conf.d /etc/
sudo rsync ./config/sddm-sugar-candy/theme.conf /usr/share/sddm/themes/sugar-candy/
echo "[DONE] SDDM configured."

sleep 1

echo "Create default user directories..."
xdg-user-dirs-update
echo "[DONE] Default dirs created."

sleep 1
echo "Installing executables ..."
cp ./bin/* ~/.local/bin

sleep 1

# Fonts
echo "Downloading & copying fonts to directories ..."
rm -rf ~/.local/share/{themes,fonts}
mkdir -p ~/.local/share/{themes,fonts}
git clone https://github.com/jadnw/Jetka.git
rsync Jetka/patched/Jetka/* ~/.local/share/fonts/
rm -rf Jetka
rsync ./fonts/local/* ~/.local/share/fonts/
fc-cache -r
echo "[DONE] Fonts copied to ~/.local/share/fonts & /usr/share/fonts."

# Run Docker with current user privileges
sudo usermod -aG docker $USER

sleep 1

echo "Copying configuration files to their locations ..."
# Copy common configs
rm -rf ~/.config
mkdir -p ~/.config
rsync --recursive ./config/{alacritty,btop,fish,fontconfig,gtk-3.0,gtk-4.0,imv,qutebrowser,rofi,sway,swaylock,swaync,waybar,zathura,starship.toml,chromium-flags.conf,chrome-flags.conf} ~/.config/
# Copy common extra configs
rsync ./extras/.gitconfig ~/
sudo rsync --recursive ./extras/reflector /etc/xdg/
# sudo rsync --recursive ./extras/timeshift /etc/
echo "[DONE] Config files copied."

# Install GTK themes
echo "Downloading & copying Gemstones GTK themes"
git clone https://github.com/jadnw/gemstones.gtk.git
cp -R gemstones.gtk/themes/* ~/.local/share/themes/
rm -rf gemstones.gtk
echo "[DONE] Gemstones GTK themes copied."

sleep 1

# Set greeting wallpaper
echo "Setting wallpapers ..."
mkdir -p ~/.config/wallpapers
rsync ./wallpapers/{wallpaper.jpg,lockscreen.jpg} ~/.config/wallpapers/
sudo rsync ./wallpapers/greeting.jpg /usr/share/sddm/themes/sugar-candy/
echo "[DONE] Wallpapers set."

# Install node
echo "Install Node v18 ..."
fnm install v18
echo "[DONE] Node v18 installed."

# Remove build dependencies
echo "Removing build dependencies ..."
set i3_installed (paru -Qs i3-wm | grep "local/")
if test -n "$i3_installed"
  paru -Rns --noconfirm i3-wm
end

sleep 1

paru -Rns --noconfirm (paru -Qdtq)
echo "[DONE] Dependencies removed."
